// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"

	amqp "github.com/streadway/amqp"

	mock "github.com/stretchr/testify/mock"

	trace "go.opentelemetry.io/otel/trace"
)

// IConsumer is an autogenerated mock type for the IConsumer type
type IConsumer[T any] struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *IConsumer[T]) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Consume provides a mock function with given fields: msg, dependencies
func (_m *IConsumer[T]) Consume(msg interface{}, dependencies T) error {
	ret := _m.Called(msg, dependencies)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, T) error); ok {
		r0 = rf(msg, dependencies)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMetrics provides a mock function with given fields:
func (_m *IConsumer[T]) GetMetrics() (int, int, int) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 int
	var r1 int
	var r2 int
	if rf, ok := ret.Get(0).(func() (int, int, int)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func() int); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(int)
	}

	return r0, r1, r2
}

// HealthCheck provides a mock function with given fields:
func (_m *IConsumer[T]) HealthCheck() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsConsumed provides a mock function with given fields: msg
func (_m *IConsumer[T]) IsConsumed(msg string) bool {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for IsConsumed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// bindQueue provides a mock function with given fields: channel, snakeTypeName, span
func (_m *IConsumer[T]) bindQueue(channel *amqp.Channel, snakeTypeName string, span trace.Span) error {
	ret := _m.Called(channel, snakeTypeName, span)

	if len(ret) == 0 {
		panic("no return value specified for bindQueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*amqp.Channel, string, trace.Span) error); ok {
		r0 = rf(channel, snakeTypeName, span)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// closeChannel provides a mock function with given fields: channel, span
func (_m *IConsumer[T]) closeChannel(channel *amqp.Channel, span trace.Span) {
	_m.Called(channel, span)
}

// consumeMessages provides a mock function with given fields: channel, queueName, span
func (_m *IConsumer[T]) consumeMessages(channel *amqp.Channel, queueName string, span trace.Span) (<-chan amqp.Delivery, error) {
	ret := _m.Called(channel, queueName, span)

	if len(ret) == 0 {
		panic("no return value specified for consumeMessages")
	}

	var r0 <-chan amqp.Delivery
	var r1 error
	if rf, ok := ret.Get(0).(func(*amqp.Channel, string, trace.Span) (<-chan amqp.Delivery, error)); ok {
		return rf(channel, queueName, span)
	}
	if rf, ok := ret.Get(0).(func(*amqp.Channel, string, trace.Span) <-chan amqp.Delivery); ok {
		r0 = rf(channel, queueName, span)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan amqp.Delivery)
		}
	}

	if rf, ok := ret.Get(1).(func(*amqp.Channel, string, trace.Span) error); ok {
		r1 = rf(channel, queueName, span)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// declareExchange provides a mock function with given fields: channel, snakeTypeName, span
func (_m *IConsumer[T]) declareExchange(channel *amqp.Channel, snakeTypeName string, span trace.Span) error {
	ret := _m.Called(channel, snakeTypeName, span)

	if len(ret) == 0 {
		panic("no return value specified for declareExchange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*amqp.Channel, string, trace.Span) error); ok {
		r0 = rf(channel, snakeTypeName, span)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// declareQueue provides a mock function with given fields: channel, snakeTypeName, span
func (_m *IConsumer[T]) declareQueue(channel *amqp.Channel, snakeTypeName string, span trace.Span) (amqp.Queue, error) {
	ret := _m.Called(channel, snakeTypeName, span)

	if len(ret) == 0 {
		panic("no return value specified for declareQueue")
	}

	var r0 amqp.Queue
	var r1 error
	if rf, ok := ret.Get(0).(func(*amqp.Channel, string, trace.Span) (amqp.Queue, error)); ok {
		return rf(channel, snakeTypeName, span)
	}
	if rf, ok := ret.Get(0).(func(*amqp.Channel, string, trace.Span) amqp.Queue); ok {
		r0 = rf(channel, snakeTypeName, span)
	} else {
		r0 = ret.Get(0).(amqp.Queue)
	}

	if rf, ok := ret.Get(1).(func(*amqp.Channel, string, trace.Span) error); ok {
		r1 = rf(channel, snakeTypeName, span)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// handleError provides a mock function with given fields: logMessage, err, span
func (_m *IConsumer[T]) handleError(logMessage string, err error, span trace.Span) error {
	ret := _m.Called(logMessage, err, span)

	if len(ret) == 0 {
		panic("no return value specified for handleError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, error, trace.Span) error); ok {
		r0 = rf(logMessage, err, span)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// handleMessage provides a mock function with given fields: ctx, span, d, dependencies
func (_m *IConsumer[T]) handleMessage(ctx context.Context, span trace.Span, d amqp.Delivery, dependencies T) error {
	ret := _m.Called(ctx, span, d, dependencies)

	if len(ret) == 0 {
		panic("no return value specified for handleMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, trace.Span, amqp.Delivery, T) error); ok {
		r0 = rf(ctx, span, d, dependencies)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// openChannel provides a mock function with given fields: ctx, span
func (_m *IConsumer[T]) openChannel(ctx context.Context, span trace.Span) (*amqp.Channel, error) {
	ret := _m.Called(ctx, span)

	if len(ret) == 0 {
		panic("no return value specified for openChannel")
	}

	var r0 *amqp.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, trace.Span) (*amqp.Channel, error)); ok {
		return rf(ctx, span)
	}
	if rf, ok := ret.Get(0).(func(context.Context, trace.Span) *amqp.Channel); ok {
		r0 = rf(ctx, span)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, trace.Span) error); ok {
		r1 = rf(ctx, span)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// setupExchangeQueue provides a mock function with given fields: channel, snakeTypeName, span
func (_m *IConsumer[T]) setupExchangeQueue(channel *amqp.Channel, snakeTypeName string, span trace.Span) error {
	ret := _m.Called(channel, snakeTypeName, span)

	if len(ret) == 0 {
		panic("no return value specified for setupExchangeQueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*amqp.Channel, string, trace.Span) error); ok {
		r0 = rf(channel, snakeTypeName, span)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIConsumer creates a new instance of IConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIConsumer[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *IConsumer[T] {
	mock := &IConsumer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
