// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"

	amqp "github.com/streadway/amqp"

	mock "github.com/stretchr/testify/mock"

	otel "github.com/NekKkMirror/go-app/internal/pkg/otel"

	trace "go.opentelemetry.io/otel/trace"
)

// IPublisher is an autogenerated mock type for the IPublisher type
type IPublisher struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *IPublisher) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMetrics provides a mock function with given fields:
func (_m *IPublisher) GetMetrics() (int, int, int) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 int
	var r1 int
	var r2 int
	if rf, ok := ret.Get(0).(func() (int, int, int)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func() int); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(int)
	}

	return r0, r1, r2
}

// HealthCheck provides a mock function with given fields:
func (_m *IPublisher) HealthCheck() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsPublished provides a mock function with given fields: msg
func (_m *IPublisher) IsPublished(msg string) bool {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for IsPublished")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Publish provides a mock function with given fields: msg
func (_m *IPublisher) Publish(msg interface{}) error {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// closeChannel provides a mock function with given fields: channel, span
func (_m *IPublisher) closeChannel(channel *amqp.Channel, span trace.Span) {
	_m.Called(channel, span)
}

// createPublishingMessage provides a mock function with given fields: data, correlationID, msgID, exchange, headers, span
func (_m *IPublisher) createPublishingMessage(data []byte, correlationID string, msgID string, exchange string, headers otel.AMQPHeadersCarrier, span trace.Span) amqp.Publishing {
	ret := _m.Called(data, correlationID, msgID, exchange, headers, span)

	if len(ret) == 0 {
		panic("no return value specified for createPublishingMessage")
	}

	var r0 amqp.Publishing
	if rf, ok := ret.Get(0).(func([]byte, string, string, string, otel.AMQPHeadersCarrier, trace.Span) amqp.Publishing); ok {
		r0 = rf(data, correlationID, msgID, exchange, headers, span)
	} else {
		r0 = ret.Get(0).(amqp.Publishing)
	}

	return r0
}

// declareExchange provides a mock function with given fields: channel, exchange, span
func (_m *IPublisher) declareExchange(channel *amqp.Channel, exchange string, span trace.Span) error {
	ret := _m.Called(channel, exchange, span)

	if len(ret) == 0 {
		panic("no return value specified for declareExchange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*amqp.Channel, string, trace.Span) error); ok {
		r0 = rf(channel, exchange, span)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// getCorrelationID provides a mock function with given fields: ctx
func (_m *IPublisher) getCorrelationID(ctx context.Context) string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getCorrelationID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// handleError provides a mock function with given fields: logMessage, err, span
func (_m *IPublisher) handleError(logMessage string, err error, span trace.Span) error {
	ret := _m.Called(logMessage, err, span)

	if len(ret) == 0 {
		panic("no return value specified for handleError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, error, trace.Span) error); ok {
		r0 = rf(logMessage, err, span)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// openChannel provides a mock function with given fields: span
func (_m *IPublisher) openChannel(span trace.Span) (*amqp.Channel, error) {
	ret := _m.Called(span)

	if len(ret) == 0 {
		panic("no return value specified for openChannel")
	}

	var r0 *amqp.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(trace.Span) (*amqp.Channel, error)); ok {
		return rf(span)
	}
	if rf, ok := ret.Get(0).(func(trace.Span) *amqp.Channel); ok {
		r0 = rf(span)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(trace.Span) error); ok {
		r1 = rf(span)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// publishMessageWithRetry provides a mock function with given fields: channel, exchange, message, span
func (_m *IPublisher) publishMessageWithRetry(channel *amqp.Channel, exchange string, message amqp.Publishing, span trace.Span) error {
	ret := _m.Called(channel, exchange, message, span)

	if len(ret) == 0 {
		panic("no return value specified for publishMessageWithRetry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*amqp.Channel, string, amqp.Publishing, trace.Span) error); ok {
		r0 = rf(channel, exchange, message, span)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIPublisher creates a new instance of IPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPublisher {
	mock := &IPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
